language: ruby

rvm:
  - 2.3.0
  - 2.0.0-p598 # CentOS 7
  - 2.1.5 # Debian 8

cache: bundler

before_install: gem install bundler -v 1.11.2

notifications:
  email:
    recipients:
      - mezuro-core@lists.ime.usp.br
    on_success: change
    on_failure: always
